#!/bin/bash

echo "Compiling BAMtoGASV"
#Compile software
pushd PipelineSoftware/bam2gasv
	make
popd

echo "Compiling GASV"
pushd PipelineSoftware/gasv
	./install
popd

echo "Compiling interval counting pipeline"
pushd PipelineSoftware/intervalCountingPipeline
	./install
popd

echo "Compiling theta"
pushd PipelineSoftware/theta
	./install
popd

echo "Compiling virtual SNP array"
pushd PipelineSoftware/virtualSNPArray
	mkdir bin
	javac java/*.java -classpath ".:jars/sam-1.78.jar" -d bin
popd

echo "Verifying python dependencies"
#Install luigi and tornado
pip install luigi
pip install tornado

#Download SNP File

