#!/bin/bash

echo "Compiling BAMtoGASV"
#Compile software
pushd PipelineSoftware/bam2gasv
	make
popd

echo "Compiling GASV"
pushd PipelineSoftware/gasv
	./install
popd

echo "Compiling interval counting pipeline"
pushd PipelineSoftware/intervalCountingPipeline
	./install
popd

echo "Compiling theta"
pushd PipelineSoftware/theta
	./install
popd

echo "Compiling virtual SNP array"
pushd PipelineSoftware/virtualSNPArray
	mkdir bin
	javac java/*.java -classpath ".:jars/sam-1.78.jar" -d bin
popd

echo "Verifying python dependencies"
#Install luigi and tornado
pip install luigi
pip install tornado

echo "Downloading SNP files"
#Download SNP File
if [ ! -f "PipelineSoftware/virtualSNPArray/AffySNP6.0_hg18.txt.formatted" ]; then
    echo "Downloading hg18 SNPS"
    curl https://s3.amazonaws.com/SNP_files/AffySNP6.0_hg18.txt.formatted -o PipelineSoftware/virtualSNPArray/AffySNP6.0_hg18.txt.formatted
else
    echo "hg18 SNPs exist, not downloading"
fi
if [ ! -f "PipelineSoftware/virtualSNPArray/1000G_hg19_snps.tsv" ]; then
    echo "Downloading hg19 SNPS"
    curl https://s3.amazonaws.com/SNP_files/1000G_hg19_snps.tsv -o PipelineSoftware/virtualSNPArray/1000G_hg19_snps.tsv
else
    echo "hg19 SNPS exist, not downloading"
fi



