#include <stdio.h>
#include <assert.h>
#include "b2g_bam.h"
#include "b2g_signal.h"
#include "b2g_conc_pair.h"
#include "io.h"
#include "list.h"
#include "b2g_disc_pair.h"
#include "b2g_chromosome.h"

// CONSTRUCTORS

b2g_conc_pair_t *b2g_conc_pair(unsigned int chr, unsigned int lstart, unsigned int rend) {
  b2g_conc_pair_t *pair = b2g_malloc(sizeof(b2g_conc_pair_t));
  b2g_conc_pair_init(pair, chr, lstart, rend);
  return pair;
}

void b2g_conc_pair_init(b2g_conc_pair_t *pair, unsigned int chr, unsigned int lstart, unsigned int rend) {
  pair->lstart = lstart;
  pair->conc = 1;
  pair->chr = chr;
  pair->rend = rend;
}

b2g_conc_pair_t *b2g_disc_pair2b2g_conc_pair(b2g_disc_pair_t *pair) {
  b2g_conc_pair_t *cpair = b2g_conc_pair(b2g_disc_pair_lchr(pair), 
				 b2g_disc_pair_lstart(pair), 
				 b2g_disc_pair_rend(pair));
  return cpair;
}

/*
b2g_conc_pair_t *bams2b2g_conc_pair(b2g_bam_t *b1, b2g_bam_t *b2, b2g_chromosomes_t *chromosomes, unsigned char WRITE_LOWQ) {
  assert(b1 && b2 && is_bool(WRITE_LOWQ));
  assert(b2g_bam_chr(b1) != b2g_bam_chr(b2) || b2g_bam_start(b1) <= b2g_bam_start(b2));

  return b2g_conc_pair(b2g_bam_chr(b1), 
		   b2g_bam_start(b1),
		   b2g_bam_end(b2));
}
*/



void b2g_conc_pair_free(b2g_conc_pair_t *pair) {
  assert(pair);
  assert(b2g_conc_pairp(pair));
  free(pair);
}

int b2g_conc_pair_cmp(b2g_conc_pair_t* a, b2g_conc_pair_t* b) {
  assert(a); 
  assert(b); 
  assert(b2g_conc_pairp(a)); 
  assert(b2g_conc_pairp(b));

  return b2g_cmp(a->chr, b->chr,
		 a->lstart, b->lstart,
		 a->rend, b->rend);
}

// I/O

// Renders a human-readeable debug print for the pair.
void b2g_conc_pair_print(b2g_conc_pair_t *pair) {
  assert(pair);
  if (b2g_signal_eof(pair)) printf("#B2G_SIGNAL_EOF");
  else if (b2g_signal_err(pair)) printf("#B2G_SIGNAL_ERR");
  else {
    assert(b2g_conc_pairp(pair));
    printf("#b2g_conc_pair_t(%d %d %d)", pair->chr, pair->lstart, pair->rend);
  }
}

// Writes a representation of the pair to a file that can be read back in with read.
void b2g_conc_pair_write(b2g_conc_pair_t *pair, FILE *out) {
  assert(pair);
  assert(b2g_conc_pairp(pair));
  assert(out);

  fprintf(out, "%d\t%d\t%d\n", pair->chr, pair->lstart, pair->rend);
}

// Writes the final output format of the pair to a file. Cannot be read back in with read.
void b2g_conc_pair_display(b2g_conc_pair_t *pair, FILE *out, b2g_chromosomes_t *chromasomes) {
  assert(pair && b2g_conc_pairp(pair) && out);
  fprintf(out, "%d\t%d\t%d\n", b2g_conc_pair_chr(pair), b2g_conc_pair_lstart(pair), b2g_conc_pair_rend(pair));
}

// Reads a representation of a pair from a file that was generated by write.
int b2g_conc_pair_read(b2g_conc_pair_t *pair, FILE *in) {  
  assert(in);  
  if (!pair) return 0;

  int chr, amt_read;
  if (-1 == fscanf(in, "%d %d %d\n%n", &chr, &pair->lstart, &pair->rend, &amt_read)) {
    bzero(pair, sizeof(b2g_conc_pair_t));
    return B2G_SIGNAL_EOF;
  }
  pair->conc = 1;
  pair->chr = chr;  
  return amt_read;
}
