#include <assert.h>
#include <string.h>
#include <stdio.h>
#include "btg_input2params.h"
#include "b2g_cutoff_lminlmax.h"
#include "b2g_disc_pair.h"
#include "b2g_constants.h"

static void _setup_btg_input2params(char** BAM_PATH, char** OUTPUT_PREFIX, int* MAPPING_QUALITY, int* WRITE_CONCORDANT, int* WRITE_LOWQ,  int* LOW_MEMORY, int* AMBIGUOUS, int *LIBRARY_SEPARATED, int *VERBOSE, int *CUTOFF_LMINLMAX_X, int *CUTOFF_LMINLMAX_Y, b2g_cutoff_lminlmax_mode_t *CUTOFF_LMINLMAX_MODE, char **CUTOFF_LMINLMAX_NAME, int *PROPER_LENGTH, int *USE_NUMBER_READS, int *DEBUG_LEVEL, int *WRITE_SPLITREAD, int *MIN_ALIGNED_PCT, char **CHROMOSOME_NAMING, b2g_platform_t *PLATFORM, int *VALIDATION_STRINGENCY, int *GASV_PRO, int *IGNORE_DUPLICATES, int *QNAME_SORTED, int *SPLIT_BY_CHROMOSOME) {
  *BAM_PATH = *OUTPUT_PREFIX = *CHROMOSOME_NAMING = *CUTOFF_LMINLMAX_NAME = NULL;
  *WRITE_LOWQ = *WRITE_CONCORDANT = *LOW_MEMORY = *AMBIGUOUS = *VERBOSE = *DEBUG_LEVEL = *WRITE_SPLITREAD = *VALIDATION_STRINGENCY = *GASV_PRO = *CUTOFF_LMINLMAX_X = *CUTOFF_LMINLMAX_Y = *QNAME_SORTED = *SPLIT_BY_CHROMOSOME = 0;
  *LIBRARY_SEPARATED = *IGNORE_DUPLICATES = 1;
  *MAPPING_QUALITY = 10;
  *MIN_ALIGNED_PCT = 95;  
  *PROPER_LENGTH = 10000;
  *USE_NUMBER_READS = 500000;
  *CUTOFF_LMINLMAX_MODE = NO_MODE;
  *PLATFORM = ILLUMINA;
}

static b2g_error_t _run_btg_input2params(int argc, char **argv, char** BAM_PATH, char** OUTPUT_PREFIX, int* MAPPING_QUALITY, int* WRITE_CONCORDANT, int* WRITE_LOWQ,  int* LOW_MEMORY, int* AMBIGUOUS, int *LIBRARY_SEPARATED, int *VERBOSE, int *CUTOFF_LMINLMAX_X, int *CUTOFF_LMINLMAX_Y, b2g_cutoff_lminlmax_mode_t *CUTOFF_LMINLMAX_MODE, char **CUTOFF_LMINLMAX_NAME, int *PROPER_LENGTH, int *USE_NUMBER_READS, int *DEBUG_LEVEL, int *WRITE_SPLITREAD, int *MIN_ALIGNED_PCT, char **CHROMOSOME_NAMING, b2g_platform_t *PLATFORM, int *VALIDATION_STRINGENCY, int *GASV_PRO, int *IGNORE_DUPLICATES, int *QNAME_SORTED, int *SPLIT_BY_CHROMOSOME) {
  _setup_btg_input2params(BAM_PATH, OUTPUT_PREFIX, MAPPING_QUALITY, WRITE_CONCORDANT, WRITE_LOWQ, LOW_MEMORY, AMBIGUOUS, LIBRARY_SEPARATED, VERBOSE, CUTOFF_LMINLMAX_X, CUTOFF_LMINLMAX_Y, CUTOFF_LMINLMAX_MODE, CUTOFF_LMINLMAX_NAME, PROPER_LENGTH, USE_NUMBER_READS, DEBUG_LEVEL, WRITE_SPLITREAD, MIN_ALIGNED_PCT, CHROMOSOME_NAMING, PLATFORM, VALIDATION_STRINGENCY, GASV_PRO, IGNORE_DUPLICATES, QNAME_SORTED, SPLIT_BY_CHROMOSOME);
  
  return btg_input2params(argc, argv, BAM_PATH, OUTPUT_PREFIX, MAPPING_QUALITY, WRITE_CONCORDANT, WRITE_LOWQ, LOW_MEMORY, AMBIGUOUS, LIBRARY_SEPARATED, VERBOSE, CUTOFF_LMINLMAX_X, CUTOFF_LMINLMAX_Y, CUTOFF_LMINLMAX_MODE, CUTOFF_LMINLMAX_NAME, PROPER_LENGTH, USE_NUMBER_READS, DEBUG_LEVEL, WRITE_SPLITREAD, MIN_ALIGNED_PCT, CHROMOSOME_NAMING, PLATFORM, VALIDATION_STRINGENCY, GASV_PRO, IGNORE_DUPLICATES, QNAME_SORTED, SPLIT_BY_CHROMOSOME);
}

static void _test_btg_input2params() {
  char *BAM_PATH, *OUTPUT_PREFIX, *CHROMOSOME_NAMING, *CUTOFF_LMINLMAX_NAME;
  int WRITE_LOWQ, LIBRARY_SEPARATED, MAPPING_QUALITY, WRITE_CONCORDANT, LOW_MEMORY, AMBIGUOUS, VERBOSE, CUTOFF_LMINLMAX_X, CUTOFF_LMINLMAX_Y, PROPER_LENGTH, USE_NUMBER_READS, DEBUG_LEVEL, WRITE_SPLITREAD, MIN_ALIGNED_PCT, VALIDATION_STRINGENCY, GASV_PRO, IGNORE_DUPLICATES, QNAME_SORTED, SPLIT_BY_CHROMOSOME;
  b2g_platform_t PLATFORM;
  b2g_cutoff_lminlmax_mode_t CUTOFF_LMINLMAX_MODE;  

  
  char *argv[10][36] = {{"bam2gasv", "bam_path", "-CUTOFF_LMINLMAX", "EXACT=10,30"},
			{"bam2gasv", "bam_path", "-CUTOFF_LMINLMAX", "FILE=file_name", "-WRITE_LOWQ", "true"},
			{"bam2gasv", "bam_path", "-UNKNOWN", "true"},
			{"bam2gasv"},
			{"bam2gasv", "-WRITE_LOWQ", "true"},
			{"blah", "bam_path", "-WRITE_LOWQ", "maybe"},
			{"blah", "bam_path", "-CUTOFF_LMINLMAX", "PCT =99"},
			{"blah", "bam_path", "-MAPPING_QUALITY", "301"},
			{"blah", "bam_path", "-CUTOFF_LMINLMAX", "EXACT=100,99"},
			{"blah", "bam_path", 
			 "-OUTPUT_PREFIX", "prefix", 
			 "-CUTOFF_LMINLMAX", "PCT=99%", 
			 "-MAPPING_QUALITY", "25", 
			 "-WRITE_CONCORDANT", "true", 
			 "-WRITE_LOWQ", "true", 
			 "-LARGE_BAM", "true", 
			 "-AMBIG", "true", 
			 "-LIBRARY_SEPARATED", "all", 
			 "-VERBOSE", "false", 
			 "-PROPER_LENGTH", "5000", 
			 "-USE_NUMBER_READS", "10000", 
			 "-DEBUG_LEVEL", "3",
			 "-MIN_ALIGNED_PCT", "80",
			 "-GASVPRO", "true",
			 "-PLATFORM", "SOLiD",
			 "-QNAME_SORTED", "true",
			 "-SPLIT_BY_CHROMOSOME", "true"}};
  
  // test exact cutoff
  assert(!_run_btg_input2params(4, argv[0], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));
  assert(EXACT == CUTOFF_LMINLMAX_MODE);
  assert(10 == CUTOFF_LMINLMAX_X);
  assert(30 == CUTOFF_LMINLMAX_Y);
  assert(0 == WRITE_LOWQ);
  assert(0 == DEBUG_LEVEL);

  // test filename cutoff
  assert(!btg_input2params(6, argv[1], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));
  assert(FILENAME == CUTOFF_LMINLMAX_MODE);
  assert(!strcmp(CUTOFF_LMINLMAX_NAME, "file_name"));
  assert(1 == WRITE_LOWQ);

  // test unknown arguments
  assert(B2GERR_UNKNOWN_OPTION == btg_input2params(4, argv[2], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));

  // test too few args
  assert(B2GERR_NO_BAM_FILE_SUPPLIED == btg_input2params(1, argv[3], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));

    // test invalid bam_path
  assert(B2GERR_OPTION_WITHOUT_ARGUMENT == btg_input2params(3, argv[4], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));

  // test invalid write_lowq
  assert(B2GERR_WRITE_LOWQ == btg_input2params(4, argv[5], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));

  // test cutoff_lminlmax error handling
  assert(B2GERR_CUTOFF_LMINLMAX == btg_input2params(4, argv[6], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));

    // test range check
  assert(B2GERR_MAPPING_QUALITY == btg_input2params(4, argv[7], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));

  // test cutoff range check
  assert(B2GERR_CUTOFF_LMINLMAX == btg_input2params(4, argv[8], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));

  // test that everything reads
  assert(!btg_input2params(36, argv[9], &BAM_PATH, &OUTPUT_PREFIX, &MAPPING_QUALITY, &WRITE_CONCORDANT, &WRITE_LOWQ, &LOW_MEMORY, &AMBIGUOUS, &LIBRARY_SEPARATED, &VERBOSE, &CUTOFF_LMINLMAX_X, &CUTOFF_LMINLMAX_Y, &CUTOFF_LMINLMAX_MODE, &CUTOFF_LMINLMAX_NAME, &PROPER_LENGTH, &USE_NUMBER_READS, &DEBUG_LEVEL, &WRITE_SPLITREAD, &MIN_ALIGNED_PCT, &CHROMOSOME_NAMING, &PLATFORM, &VALIDATION_STRINGENCY, &GASV_PRO, &IGNORE_DUPLICATES, &QNAME_SORTED, &SPLIT_BY_CHROMOSOME));
  assert(!strcmp("prefix", OUTPUT_PREFIX));
  assert(PCT == CUTOFF_LMINLMAX_MODE);
  assert(99 == CUTOFF_LMINLMAX_X);
  assert(25 == MAPPING_QUALITY);
  assert(WRITE_CONCORDANT);
  assert(WRITE_LOWQ);
  assert(LOW_MEMORY);
  assert(AMBIGUOUS);
  assert(!LIBRARY_SEPARATED);
  assert(!VERBOSE);
  assert(5000 == PROPER_LENGTH);
  assert(10000 == USE_NUMBER_READS);
  assert(3 == DEBUG_LEVEL);
  assert(80 == MIN_ALIGNED_PCT);
  assert(GASV_PRO);
  assert(SOLID == PLATFORM);
  assert(1 == QNAME_SORTED);
  assert(1 == SPLIT_BY_CHROMOSOME);
}

int main() {

  _test_btg_input2params();
  return 0;
}
